FROM php:8.2-cli

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git curl unzip libzip-dev zip \
    && docker-php-ext-install pdo pdo_mysql zip

# Set working directory
WORKDIR /app

# Copy project
COPY . .

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN composer install --no-dev --optimize-autoloader

# Generate key & cache
RUN php artisan key:generate
RUN php artisan config:cache

# Start server
CMD php -S 0.0.0.0:$PORT -t public